"""referals_exp_date

Revision ID: fef08fdcb1c6
Revises: 20fec3e9cfba
Create Date: 2024-03-14 12:09:04.025421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef08fdcb1c6'
down_revision: Union[str, None] = '20fec3e9cfba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
