version: '3'

services:

  db_auth:
    image: postgres:alpine3.18
    container_name: auth_db
    restart: always
    ports:
      - "5420:5432"
    volumes:
      - db-data-auth:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=users

volumes:
  db-data-auth: