version: '3'

services:

  db_auth:
    image: postgres:alpine3.18
    container_name: auth_db
    restart: always
    networks:
      - custom
    volumes:
      - db-data-auth:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=users

  auth:
    image: referals_fastapi
    container_name: referals_fastapi
    depends_on:
      - db_auth
    build:
      context: referal_service_back/
      dockerfile: Dockerfile
    command: 'sh -c "alembic upgrade head && python main.py"'
    networks:
      - custom
    ports:
      - 8000:8000

networks:
  custom:
    driver: bridge
volumes:
  db-data-auth: